jobs:
  extract-info:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Extract Metadata
        uses: actions/github-script@v7
        with:
          script: |
            const run_id = context.runId;
            const sha = context.sha;
            console.log(`Run ID: ${run_id}`);
            console.log(`SHA: ${sha}`);
            // You can now use these variables for further API calls or processing

